### ISSUE TITLE
终端执行命令返回超时

### ISSUE THREAD

**Issue by code-scan** [antoor/antSword#1]
(Cond0r:/Users/Cond0r/Downloads/AntSword-darwin-x64) $ netstat -an
{"code":"ECONNABORTED","timeout":5000}
(Cond0r:/Users/Cond0r/Downloads/AntSword-darwin-x64) $ netstat -an > 1.txt
{"code":"ECONNABORTED","timeout":5000}
(Cond0r:/Users/Cond0r/Downloads/AntSword-darwin-x64) $ cat 1.txt|head -n 10
{"code":"ECONNABORTED","timeout":5000}

**Comment by antoor** [comment]
这是由于连接目标超时引起的错误提示 :-)
