### ISSUE TITLE
排序功能不完善

### ISSUE THREAD

**Issue by imp0wd3r** [antoor/antSword#14]
数字的排序是按最高位大小来排的，显然并不是很合理：

![screenshot from 2016-03-15 20 58 13](https://cloud.githubusercontent.com/assets/17606044/13778473/f75e474a-eaf0-11e5-9372-e9d514042f5f.png)

同理文件按大小排序也是如此，虽然给出单位了。。。。

![screenshot from 2016-03-15 21 01 36](https://cloud.githubusercontent.com/assets/17606044/13778503/23c64cce-eaf1-11e5-9a75-64510d952793.png)

Ubuntu 14.04

**Comment by antoor** [comment]
这个UI框架的排序算法就是这样，逐字进行排序。
当然是可以进行一整列数据从大到小进行排序的，但是正如第一张截图，从数据库中获取到的数据，没办法自动识别那个字段可能是可排序的整数，那个字段是字符串，所以目前这个细节暂时不考虑进行改进（需要修改框架源码，浪费精力大）。
还是感谢你的支持！
