### ISSUE TITLE
增加TODO和contribution的要求？

### ISSUE THREAD

**Issue by naijim** [antoor/antSword#19]
这样方便其他人贡献代码，对coding style也应该说明一下

**Comment by antoor** [comment]
更新日志以及TODO LIST在这：
[CHANGELOG.md](https://github.com/antoor/antSword/blob/master/CHANGELOG.md)

至于`Coding style`，如果是自己添加的文件，则按照自己喜欢的风格编写即可；如果是在原来的基础上进行改进，则根据上下文应该就知道怎么命名怎么编写了。。。（其实是我也不太在意风格这种东西[笑哭]
