### ISSUE TITLE
虚拟终端命令执行失败。。

### ISSUE THREAD

**Issue by looyun** [antoor/antSword#26]
ERROR:// java.io.IOException: Cannot run program "d": CreateProcess error=2, ϵͳÕҲ»µ½ָ¶

**Comment by antoor** [comment]
这个和你的shell有关，请自行根据数据加以修改，或者试试[https://github.com/antoor/antSword/blob/v1.1-dev/shells/custom.jsp](https://github.com/antoor/antSword/blob/v1.1-dev/shells/custom.jsp)
