### ISSUE TITLE
为什么我初始化后打开只显示一只猫

### ISSUE THREAD

**Issue by wsq1211278323** [antoor/antSword#338]
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎6
操作系统版本	22621.1992
序列号	PF3V76FA
体验	Windows Feature Experience Pack 1000.22644.1000.0
救救孩子啊！！！！
![Uploading 57KNJDGDJVBJ3_9FTVXLHKW.png…]()

**Comment by pfinal-nc** [comment]
图片看不见

**Comment by wsq1211278323** [comment]
&nbsp;


田冶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月31日(星期一) 上午9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AntSwordProject/antSword] 为什么我初始化后打开只显示一只猫 (Issue #338)





 
图片看不见

**Comment by wsq1211278323** [comment]
> 图片看不见

我好像发不过去，我邮件是1211278323@qq.com
