### ISSUE TITLE
在linux上启动报错

### ISSUE THREAD

**Issue by XiaoSong2017** [antoor/antSword#343]
- [*] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [*] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [*] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [*] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [*] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [*] 我使用的是 64 位操作系统

### Bug 详细描述

启动报如下错误：
![image](https://github.com/AntSwordProject/antSword/assets/35443773/c434dd47-3e17-4c9d-8e1c-3ef39c1c4125)

---

**Comment by Medicean** [comment]
@XiaoSong2017 参考: https://github.com/AntSwordProject/antSword/issues/318#issuecomment-1186714297
