### ISSUE TITLE
php webshell 连接mysql数据库执行SQL语句卡死一直转圈

### ISSUE THREAD

**Issue by 1rm** [antoor/antSword#344]
查询列库和表名列名正常，执行SQL语句查询数据出现卡死现象
<img width="807" alt="屏幕截图 2023-12-26 180639" src="https://github.com/AntSwordProject/antSword/assets/28972049/d98ffd35-5649-45b0-8af6-055d3517540a">

**Comment by Medicean** [comment]
@1rm  看一下是否和 #319 是一样的问题

**Comment by 1rm** [comment]
是的
