### ISSUE TITLE
Can't connect non secure ssl website

### ISSUE THREAD

**Issue by ismilent** [antoor/antSword#39]
不能连接 不安全的HTTPS站点。把证书信任忽略吧

**Comment by antoor** [comment]
目前该问题的解决办法如下：
修改`node_modules/superagent/lib/node/index.js` line 607，添加如下代码：
``` js
options.requestCert = false;
```

该BUG以后会进行这样修复：在添加shell的时候提供给用户选择是否忽略HTTPS证书，目前因在改进其他功能，所以此功能暂时搁置，望谅解！

**Comment by antoor** [comment]
在2.0-beta中已经解决（后边会以2.0正式版发布 #60 

![](http://hbimg.b0.upaiyun.com/85f68d09489c7a48f5dd522083bfec8822aafe33a36f2-lzS7Br_fw658)
