### ISSUE TITLE
程序窗口改变时,功能窗口关闭

### ISSUE THREAD

**Issue by gycain** [antoor/antSword#4]
程序最大化或者恢复正常化窗口时，里面的功能窗口全部自动关闭了。

**Comment by antoor** [comment]
不是关闭，是在调整窗口后，因为UI框架无法自适应，所以得刷新页面重新刷新UI。
这个以后可以弄个提示框，或者你有什么好的建议吗？谢谢

**Comment by SatanSec** [comment]
这个问题太严重了，切到其它窗口再切回来UI就重新刷新了。

**Comment by antoor** [comment]
@SatanSec 你用的是ubuntu吗？目前mac和win下都没发现窗口重获焦点后刷新问题。

**Comment by SatanSec** [comment]
ubuntu14.04

**Comment by antoor** [comment]
@SatanSec 可以把app.js 34-37行的监听窗口事件代码删除。

**Comment by hack2012** [comment]
我用win7 x64也有此问题。还是修改一下。

**Comment by antoor** [comment]
已修正，在用户更改窗口大小之后（调整长/宽 >= 10），弹框提示用户是否需要重启应用刷新UI。
