### ISSUE TITLE
添加localhost的webshell时提示"Path Not Found Or No Permission!"

### ISSUE THREAD

**Issue by Wyc0** [antoor/antSword#44]
导致本地中转脚本用不了, 不过可以获取到服务器路径
![screen shot 2016-04-24 at 11 53 47](https://cloud.githubusercontent.com/assets/13194609/14765429/3f23a91c-0a13-11e6-9edd-23656d3dc6d4.png)

**Comment by antoor** [comment]
这个错误提示是因为没有目标路径的**读取权限**

![](https://41.media.tumblr.com/bc8ba93f118d5f2d293fdd04e211f2d7/tumblr_o4o3ua19Qz1shvaeko1_540.jpg)

**Comment by Wyc0** [comment]
炒...确实是中转脚本有问题
