### ISSUE TITLE
随机编码器功能

### ISSUE THREAD

**Issue by antoor** [antoor/antSword#54]
编写一个通用的随机编码器`random`，作用就是在已知的编码器列表中随机选择一个进行使用。

> 代码实现很简单，有待空闲编写。

![](http://hbimg.b0.upaiyun.com/615f46c4a6bc3033ccaa55edb835d028df7576291c10b-rq4emt_fw658)

**Comment by Medicean** [comment]
这个功能在处理 CUSTOM 类型的时候会很麻烦啊。

**Comment by antoor** [comment]
@Medicean  `Custom`就不考虑这个功能就好了。。
![](http://hbimg.b0.upaiyun.com/cd3984a4fa530b402b5f69299d8ce2153e6cd2d884a5-BvG4Hy_fw658)
