### ISSUE TITLE
自定义HTTP头数据

### ISSUE THREAD

**Issue by antoor** [antoor/antSword#57]
目前的版本是可以直接通过修改代码进行HTTP HEADER修改的，但是我们希望的是：
每个不同的目标都能自定义一个自己专属的HTTP头数据，比如`Cookie`。
然后可以通过浏览网站进行动态的修改头数据，达到管理**需要登陆验证才能访问的服务端脚本**的目的。

> 目前该功能计划添加到：**shell管理->添加/编辑shell窗口**中

![](http://hbimg.b0.upaiyun.com/c968a5b1c7b0aa9ab6a580e07057719199b4f63e15047-pkevPy_fw658)

**Comment by Medicean** [comment]
加油，本来计划我来做这个功能的。

**Comment by antoor** [comment]
@Medicean 因为这个功能之前已经想好，需要改动的地方也比较多（比如数据存储设置），还有其他高级设置（比如忽略HTTPS证书）、代码重写什么，所以等弄完手上的活，我就开写了

![](http://hbimg.b0.upaiyun.com/25171187b41ef8e220de33b686505316ddd5ce351ed2e-Z4iWE2_fw658)
