### ISSUE TITLE
tomcat 5.x一句话无法执行命令

### ISSUE THREAD

**Issue by getcode2git** [antoor/antSword#6]
执行命令报错提示：

`ERROR:// java.io.IOException: Cannot run program "d": CreateProcess error=2, 系统找不到指定的文件。`

**Comment by antoor** [comment]
这个原因大概是JSP服务端处理出错，因为提交的数据和原先的菜刀支持的服务端脚本有出入，所以会有很多不兼容。
具体可以修改代码进行调试
