### ISSUE TITLE
下载大文件界面会卡死

### ISSUE THREAD

**Issue by firexp** [antoor/antSword#7]
![qq 20160314104049](https://cloud.githubusercontent.com/assets/8402161/13733708/546b7e74-e9d1-11e5-8179-22aa354e9d3c.png)

**Comment by antoor** [comment]
文件有多大=.=
目前下载是没有断点的，要是太大，可能会引起内存撑爆～

**Comment by zypperin** [comment]
大文件最好复制到web目录，然后用下载工具或网盘下载

**Comment by firexp** [comment]
文件大概70M，下载完成时程序内存占用在400M，不至于把内存撑爆

**Comment by antoor** [comment]
此问题已经在最新的1.2开发版本中解决 :)
[https://github.com/antoor/antSword/tree/v1.2-dev](https://github.com/antoor/antSword/tree/v1.2-dev)
