### ISSUE TITLE
读取window服务器上得文件，不管设置什么编码 中文都会乱码

### ISSUE THREAD

**Issue by zhangweiwei0326** [antoor/antSword#8]
读取window服务器上得文件，不管设置什么编码 中文都会乱码

**Comment by hack2012** [comment]
确实有此问题，刚才才试用过，GBK，UTF-8都会有此问题，希望作者修复。

**Comment by antoor** [comment]
不知道你的windows服务器采用的系统编码是什么呢？
自定义编码添加在source/base/encodes.jsx中，可自行添加iconv-lite模块所支持的编码列表

**Comment by zypperin** [comment]
编码是个大坑，试试把shell用记事本打开，另存为..选utf-8 或者ansi，然后重新传到server上

**Comment by hack2012** [comment]
我服务器就是Wamp，然后shell是最常见的eval的，ansi格式的。

**Comment by Medicean** [comment]
@zhangweiwei0326 @hack2012 

Win  下 PHP_Eval 中文测试：

![win_encoding_php_file](https://cloud.githubusercontent.com/assets/6082020/14759176/42f601fc-094b-11e6-8930-631f21bcd91e.png)

Win 下 ASPX 中文测试：

![win_encoding_aspx_file](https://cloud.githubusercontent.com/assets/6082020/14759210/7b82b15e-094c-11e6-9cba-3b8119f203b0.png)

![win_encoding_aspx_ter](https://cloud.githubusercontent.com/assets/6082020/14759211/85215634-094c-11e6-8045-42e372cddf31.png)

Have fun !
