### ISSUE TITLE
mac版启动器自动下载源码的源是否有误？

### ISSUE THREAD

**Issue by neargle** [antoor/antSword#83]
加载器选择工作目录之后自动下载并解压，会报错，不能正常启动。
我看了一下下载的是master分支上面的源码。
于是git clone源码之后，checkout到v2.0-beta，重新设置目录。
之后软件可以正常启动。

![image](https://cloud.githubusercontent.com/assets/7868679/23454798/643829f0-fea8-11e6-94cc-e994f0e106fe.png)

感觉应该是下载 https://github.com/antoor/antSword/archive/v2.0-beta.zip 并解压才对

**Comment by Medicean** [comment]
@neargle  2.0 暂未发布，发布后会将 v2.0-beta 分支合并至 master 分支
