### ISSUE TITLE
蚁剑使用默认的菜刀一句话php shell出错

### ISSUE THREAD

**Issue by tennc** [antoor/antSword#9]
蚁剑使用默认的菜刀一句话php shell出错，系统win10  源码编译，使用默认的配置（编码为默认），连接shell出错（不能正常操作），更改编码 base64 or hex 则正常操作。
jsp 园长修改菜刀shell  默认正常，若使用base64 or hex 则出错~~

**Comment by antoor** [comment]
默认配置为未加密的源码数据，有引号等特殊字符，如果服务器开了魔术引导或者其他防御，那肯定执行不了了。
同理，jsp之类的shell用的都是custom模板，此模板目前提供三个编码器，每个编码器发送的数据都不一样，具体怎么处理看服务端脚本了。
